services:
  postgres:
    image: postgres:16
    container_name: postgres-local
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: meu_banco
    ports:
      - "5434:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
  