-- 50 INSERTs para a tabela categoria
INSERT INTO categoria (nome, debito, credito, id_pai, descricao, situacao) VALUES
('Receitas Operacionais', false, true, NULL, 'Categoria principal para todas as receitas operacionais da empresa', 'ATIVO'),
('Despesas Administrativas', true, false, NULL, 'Categoria principal para despesas administrativas', 'ATIVO'),
('Despesas Comerciais', true, false, NULL, 'Categoria para despesas relacionadas à área comercial', 'ATIVO'),
('Despesas Financeiras', true, false, NULL, 'Categoria para despesas financeiras e juros', 'ATIVO'),
('Receitas Financeiras', false, true, NULL, 'Categoria para receitas financeiras e rendimentos', 'ATIVO'),
('Vendas de Produtos', false, true, 1, 'Receitas provenientes da venda de produtos', 'ATIVO'),
('Vendas de Serviços', false, true, 1, 'Receitas provenientes da prestação de serviços', 'ATIVO'),
('Salários e Ordenados', true, false, 2, 'Despesas com pagamento de salários e ordenados', 'ATIVO'),
('Encargos Sociais', true, false, 2, 'Encargos sociais sobre a folha de pagamento', 'ATIVO'),
('Aluguel', true, false, 2, 'Despesas com aluguel de imóveis', 'ATIVO'),
('Energia Elétrica', true, false, 2, 'Despesas com energia elétrica', 'ATIVO'),
('Água e Esgoto', true, false, 2, 'Despesas com água e esgoto', 'ATIVO'),
('Telefone e Internet', true, false, 2, 'Despesas com telefone e internet', 'ATIVO'),
('Material de Escritório', true, false, 2, 'Despesas com material de escritório', 'ATIVO'),
('Comissões de Vendas', true, false, 3, 'Comissões pagas sobre vendas realizadas', 'ATIVO'),
('Publicidade e Propaganda', true, false, 3, 'Despesas com publicidade e campanhas publicitárias', 'ATIVO'),
('Marketing Digital', true, false, 3, 'Despesas com marketing digital e mídias sociais', 'ATIVO'),
('Despesas com Eventos', true, false, 3, 'Despesas relacionadas a eventos e feiras', 'ATIVO'),
('Juros Pagos', true, false, 4, 'Juros pagos sobre empréstimos e financiamentos', 'ATIVO'),
('Tarifas Bancárias', true, false, 4, 'Tarifas e taxas bancárias', 'ATIVO'),
('Juros Recebidos', false, true, 5, 'Juros recebidos sobre aplicações financeiras', 'ATIVO'),
('Descontos Obtidos', false, true, 5, 'Descontos obtidos em compras à vista', 'ATIVO'),
('Manutenção de Equipamentos', true, false, 2, 'Despesas com manutenção de equipamentos', 'ATIVO'),
('Seguros', true, false, 2, 'Despesas com seguros diversos', 'ATIVO'),
('Viagens e Hospedagem', true, false, 2, 'Despesas com viagens e hospedagem', 'ATIVO'),
('Despesas com Veículos', true, false, 2, 'Despesas com manutenção e combustível de veículos', 'ATIVO'),
('Tributos e Impostos', true, false, 2, 'Despesas com tributos e impostos', 'ATIVO'),
('Honorários Contábeis', true, false, 2, 'Honorários pagos a contadores', 'ATIVO'),
('Honorários Advocatícios', true, false, 2, 'Honorários pagos a advogados', 'ATIVO'),
('Treinamentos e Cursos', true, false, 2, 'Despesas com treinamentos e cursos para funcionários', 'ATIVO'),
('Projetos Especiais', true, false, NULL, 'Categoria para projetos especiais e eventuais', 'ATIVO'),
('Receitas Não Operacionais', false, true, NULL, 'Categoria para receitas não operacionais', 'ATIVO'),
('Descontos Concedidos', true, false, 3, 'Descontos concedidos aos clientes', 'ATIVO'),
('Devoluções de Vendas', true, false, 1, 'Receitas negativas por devoluções de vendas', 'ATIVO'),
('Multas e Juros Recebidos', false, true, 5, 'Multas e juros recebidos de clientes', 'ATIVO'),
('Receitas com Aluguel', false, true, 32, 'Receitas provenientes de aluguéis recebidos', 'ATIVO'),
('Ganhos de Capital', false, true, 32, 'Ganhos de capital em aplicações financeiras', 'ATIVO'),
('Doações Recebidas', false, true, 32, 'Doações e contribuições recebidas', 'ATIVO'),
('Multas e Penalidades Pagas', true, false, 4, 'Multas e penalidades pagas', 'ATIVO'),
('Depreciação', true, false, 2, 'Despesas com depreciação de ativos', 'ATIVO'),
('Amortização', true, false, 2, 'Despesas com amortização de ativos', 'ATIVO'),
('Despesas com TI', true, false, 2, 'Despesas com tecnologia da informação', 'ATIVO'),
('Licenças de Software', true, false, 41, 'Despesas com licenças de software', 'ATIVO'),
('Serviços de Cloud', true, false, 41, 'Despesas com serviços de cloud computing', 'ATIVO'),
('Categoria Inativa 1', true, false, NULL, 'Categoria exemplo para situação inativa', 'INATIVO'),
('Categoria Inativa 2', false, true, NULL, 'Outra categoria exemplo para situação inativa', 'INATIVO'),
('Despesas Canceladas', true, false, 2, 'Categoria para registro de despesas canceladas', 'INATIVO'),
('Receitas Temporárias', false, true, 1, 'Receitas temporárias e sazonais', 'ATIVO'),
('Despesas Temporárias', true, false, 2, 'Despesas temporárias e sazonais', 'ATIVO'),
('Receitas Diversas', false, true, 1, 'Receitas diversas não categorizadas', 'ATIVO'),
('Despesas Diversas', true, false, 2, 'Despesas diversas não categorizadas', 'ATIVO');
